# https://docs.streamlit.io/develop/api-reference/configuration/config.toml

[theme]
# Primary Color (For Buttons, Highlights, and CTAs)
primaryColor = "#faf9f6"

# Main Content Background (Clean and Minimal)
backgroundColor = "#fffff0"

# Sidebar/Interactive Widgets Background (Elegant and Eye-Calming)
secondaryBackgroundColor = "#f0fae6"

# Text Color (Readable and Elegant)
textColor = "#2E2E2E"

# Font Family
font = "sans serif"
# Modern fonts like 'sans serif' 'Roboto', 'Nunito', or 'Open Sans'


[client]
toolbarMode = "auto"

[server]
address = "127.0.0.1"
port = 8501
runOnSave = true

[browser]
# serverAddress = "127.0.0.1"
# serverPort = 8501
gatherUsageStats = false
