# https://docs.streamlit.io/develop/api-reference/configuration/config.toml

[theme]

backgroundColor="#d9e0fe"
secondaryBackgroundColor="#f9fafb"
textColor="#2f3828"
font = "sans serif"

[client]
toolbarMode = "auto"

[server]
address = "127.0.0.1"
port = 8501
runOnSave = true

[browser]
# serverAddress = "127.0.0.1"
# serverPort = 8501
gatherUsageStats = false
